FROM golang:1.15.6

WORKDIR /go/src/app

# Copy source code in workdir
#COPY src/api .
#COPY cmd/main .
COPY . .

RUN go get -d -v ./...
RUN go install -v ./...

# Create output file main from golang project
#RUN go build -o main .
RUN go build cmd/main/main.go

# execute te main file
CMD ["./main"]